title: "anatolischejongen"
description: "Mijn persoolijke blog"
url: "https://anatolischejongen.github.io"
baseurl: "/anatolischejongen"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme   # ← BUNU EKLE
  - jekyll-feed
  - jekyll-seo-tag

navbar-links:
  Blog: /blog/
  About: /over
