title: "Said — NL Blog"
description: "Korte Nederlandstalige stukjes – elke week één."
url: "https://anatolischejongen.github.io"
baseurl: "/anatolischejongen"

# Tema kapalı (mavi barı kaldır)
theme:

plugins:
  - jekyll-feed
  - jekyll-seo-tag
